Refactor cluster reconciler
ContainerSolutions/pre-scaling-operator pull request #4
Opened 2021-02-22 15:20 UTC by andreas131989

Changes:
- Refactored the clusterscalingstate controller to reuse the reconciler functions
- Refactored the namespace reconciler to cover both cluster and namespace operations. That way we avoid duplicate functions
- Added via kubebuilder the right permissions for the reconciler to list/watch/update/patch the deployments. Also generated the rbac manifests according to these changes

2021-02-22 16:18 UTC, chris-cmsoft requested changes

2021-02-22 16:18 UTC, chris-cmsoft commented on config/rbac/role.yaml
> +  - watch
We only need get,list,watch,update, and patch here. 
Any reason we need create and delete ?

2021-02-22 16:18 UTC, chris-cmsoft commented on internal/reconciler/reconciler.go
> +		finalState, err := GetAppliedState(ctx, _client, deployment.Namespace, stateDefinitions, clusterState)
Calling to fetch applied state should only happen once per namespace, as it calculates a state for namespaces rather than deployments.

2021-02-22 16:18 UTC, chris-cmsoft commented on controllers/clusterscalingstate_controller.go
> +	err = reconciler.StateReconciler(ctx, r.Client, "", clusterStateDefinitions, states.State{})
The idea here, was to loop the namespaces inside this reconcile function, and called ReconcileNamespace for each of those namespaces. 
That way we can check for correct rolebindings before we even try to reconcile a namespace. 

That cleans it up so we can reuse both Reconcile NS and reconcile Deployment, depending on which change we observe.

2021-02-22 16:18 UTC, chris-cmsoft commented on controllers/clusterscalingstate_controller.go
> +	err = reconciler.StateReconciler(ctx, r.Client, "", clusterStateDefinitions, states.State{})
Passing in a empty namespace, and letting it fetch all, also creates an implicit all-namespaces call, which we want to avoid, as we explicitly want to specify if for scenarios where we do not have cluster-wide access

2021-02-22 16:40 UTC, andreas131989 commented on config/rbac/role.yaml
> +  - watch
Nope, I was just testing generally permissions. I'll remove the create/delete

2021-02-22 16:55 UTC, andreas131989 commented on controllers/clusterscalingstate_controller.go
> +	err = reconciler.StateReconciler(ctx, r.Client, "", clusterStateDefinitions, states.State{})
Ah gotcha. Yeah that'll work too. 
I have some reservations about looping all namespaces and then all deployments in each namespace that's why I thought of starting in a simpler way. As in really big clusters this can be quite heavy and slow. So was thinking more of a generic use, rather than when we have more constraints (like not being able to list resources on a cluster level etc).

2021-02-22 16:58 UTC, andreas131989 commented on internal/reconciler/reconciler.go
> +		finalState, err := GetAppliedState(ctx, _client, deployment.Namespace, stateDefinitions, clusterState)
Yeah that's a byproduct of not looping all namespaces :P

2021-02-23 11:41 UTC, chris-cmsoft commented on controllers/clusterscalingstate_controller.go
> +	err = reconciler.StateReconciler(ctx, r.Client, "", clusterStateDefinitions, states.State{})
If we loop all deployments, we will have to fetch namespaces details and compute state definitions for each anyway. 
We'll end up with the same amount of calls to the client. 

As it is a cached client, the costs of this are neglegible. 

Looping namespaces allows us to solve some of the higher level security needs such as no all-namespaces access, as well as being able to check rolebindings in each of those namespaces once as we loop.

Where as assuming all-namespaces, and then failing to the loop, solves both problems separately. 
Whereas looping namespaces from the start solves both, with similar performance concerns as the other way around.

2021-02-25 15:10 UTC, chris-cmsoft approved these changes

2021-02-25 15:10 UTC, chris-cmsoft commented on controllers/clusterscalingstate_controller.go
> +		err = reconciler.ReconcileNamespace(ctx, r.Client, namespace.Name, clusterStateDefinitions, states.State{})
We can do in the next PR, but the last states.State{} represents the ClusterScalingState. This allows us to fetch it ones for the reconciliation loop, and then use that internally to calculate the namespace state.

2021-02-25 15:18 UTC, merged