Support default annotation
ContainerSolutions/pre-scaling-operator pull request #7
Opened 2021-03-16 09:28 UTC by PathogenDE

Pull request containing the Default fallback feature as well as prefilters on deployment and deploymentconfig. They can control when the reconcilation is triggered, reducing the calls to the loop by a lot.
There will be only reconcilation be done if the deployment opts out (to fall back to default) or when an annotation is changed and the deployment is opted in, or when the the deployment is opted in from false -> true.

2021-03-16 11:03 UTC, andreas131989 commented on .vscode/launch.json
> +}
Do we need this in the master branch? Maybe we can add .vscode to .gitignore? 
Not sure if that's useful for everybody that could use the repo

2021-03-16 11:09 UTC, andreas131989 commented on controllers/deployment_watch_controller.go
> -
This part is not removed in the deploymentConfig watcher. Which one is correct? :)

2021-03-16 11:13 UTC, andreas131989 commented on pkg/utils/labels/labels_test.go
> +
Maybe we can put a test here :) ?

2021-03-16 11:15 UTC, PathogenDE commented on .vscode/launch.json
> +}
It would certainly be useful if someone is using vscode as that configuration would work on every machine

2021-03-16 11:17 UTC, PathogenDE commented on controllers/deployment_watch_controller.go
> -
Yeah that needs to go. Removed

2021-03-16 11:30 UTC, andreas131989 commented on internal/reconciler/reconciler.go
> +	if !optinLabel {
In the ReconcileNamespace, you're passing the optinlabel as true explicitly. Then this check never executes.

2021-03-16 12:04 UTC, andreas131989 commented on internal/validations/prefilter.go
> +package validations
Do you think we can add a unit test for this one? Or you want to do it in another PR?

2021-03-16 12:05 UTC, andreas131989 commented on internal/reconciler/reconciler.go
> +		err = ReconcileDeployment(ctx, _client, deployment, finalState, true)
Maybe we can use the label itself instead of true

2021-03-16 12:09 UTC, andreas131989 commented on pkg/utils/labels/labels_test.go
> +
Actually, there was a test here. Any reason why we removed it?

2021-03-16 12:10 UTC, andreas131989 commented on internal/validations/prefilter.go
> +			newoptin := labels.GetLabelValue(newlabels, "scaler/opt-in")
The label validation was made in a way that can be used even if the label key changes. Now this builds the key in the code. I think we need to keep the more generic approach, although it is unlikely that this will change in the future.

2021-03-16 12:15 UTC, andreas131989 commented on .vscode/launch.json
> +}
Indeed, but what if the user doesn't use vscode :). Then they are pulling files that are of no use to them.
I would typically consider that local env stuff are not part of the source code of the operator, but happy to see what other think!

2021-03-16 12:19 UTC, andreas131989 commented
I think overall looks good! Some small things mainly around adding a couple of unit tests and using the labels explicitely in the code.
The main thing to fix is the error about failing to update the deployment replicas which gets thrown sometimes. Previously this was overcome as the reconcilation loop was triggered by every single event (which was wrong), so now that it's working as it should, we need to fix this error as it sometimes scales while other times doesn't.
Nice stuff! And good idea around event filtering

2021-03-16 12:26 UTC, PathogenDE commented on internal/validations/prefilter.go
> +			newoptin := labels.GetLabelValue(newlabels, "scaler/opt-in")
We should maybe have default values somewhere so we can use them? Not necessarily configuration but so we can re-use it and would be easy to change

2021-03-16 12:27 UTC, PathogenDE commented on pkg/utils/labels/labels_test.go
> +
Oh I think this whole package can go. The code from the package is never used and with the label_validation package (that includes tests) it is obsolete

2021-03-16 14:04 UTC, andreas131989 commented on internal/validations/prefilter.go
> +			newoptin := labels.GetLabelValue(newlabels, "scaler/opt-in")
Yes you can find them in constants.go :)

2021-03-17 21:22 UTC, PathogenDE commented on internal/validations/prefilter.go
> +			annotationsnew = annotations.FilterByKeyPrefix("scaler", e.ObjectNew.GetAnnotations())
This would break on Openshift.

2021-03-17 21:23 UTC, PathogenDE commented on internal/validations/prefilter.go
> +			oldDeployment, ok1 := e.ObjectOld.(*v1.Deployment)
This would break on Openshift

2021-03-17 21:56 UTC, chris-cmsoft commented on .vscode/launch.json
> +}
These should not be included in source code. VS Code will generally populate these, and could differ from machine to machine, and is a source for conflicts of local environments.

2021-03-17 21:58 UTC, chris-cmsoft commented on internal/validations/prefilter.go
> +			oldDeployment, ok1 := e.ObjectOld.(*v1.Deployment)
This is also a possibly place where the different types we are supporting could cause lots of maintenance. 
We could consider better composition here, and use an interfaceable validation. Makes it easier to add new types, even though there will not be many.

2021-03-17 22:16 UTC, chris-cmsoft requested changes

2021-03-17 22:16 UTC, chris-cmsoft commented on internal/reconciler/reconciler.go
> +func ReconcileDeployment(ctx context.Context, _client client.Client, deployment v1.Deployment, state states.State, optinLabel bool) error {
optinLabel seems ambiguous here, and could be construed simply as the value of the label. We should change the name to something more meaningful, like `optOut`. Could a bigger sense of it's side effects. 

Just a thought though

2021-03-17 22:16 UTC, chris-cmsoft commented on internal/reconciler/reconciler.go
> +			return nil
We should use early return if statements here to avoid deep nesting. 

Instead of the above, we could use
```
if oldReplicaCount == stateReplica.Replicas {
    # Here we can return early
    return nil
}

# Here continue assuming that the case was not true
```

The same for for the inner loop.

2021-03-17 22:16 UTC, chris-cmsoft commented on internal/reconciler/reconciler.go
> +func ReconcileDeploymentConfig(ctx context.Context, _client client.Client, deploymentConfig ocv1.DeploymentConfig, state states.State, optinLabel bool) error {
Same here for renaming the input to`optOut` to avoid confusion of it's actual side effects

2021-03-17 22:16 UTC, chris-cmsoft commented on internal/reconciler/reconciler.go
> +	})
Same here for nested ifs. We should switch to early returns to make the piece more readable, as well as testable.

2021-03-17 22:16 UTC, chris-cmsoft commented on internal/validations/prefilter.go
> +			}
If there is a change, and we know we will reconcile later, return early and reconcile. 
Log a message, stating reason for reconcile, and reconcile.

2021-03-17 22:16 UTC, chris-cmsoft commented on internal/validations/prefilter.go
> +			if (annotationchange || replicaChange || !oldoptin || !newoptin) && (oldoptin || newoptin) {
Use seom early returns here to avoid complicated ifs. 
Makes testing a whole lot easier when we don't have to test all cases together, but can test them one through to the next

2021-03-17 22:16 UTC, chris-cmsoft commented on pkg/utils/labels/labels.go
> +		detect, _ = strconv.ParseBool(v)
return early. No need to loop the whole list if the first item is true. 

```
if v, found := labels[optin]; !found {
    return false
}
optedIn, err := strconv.ParseBool(labels[optin])
if err != nil {
    log.Errorf("Failed to parse optin label. Expected bool string, got %s", labels[optin])
    return false
}
return optedIn
```

Makes it a bit easier to read and test

2021-03-18 09:39 UTC, chris-cmsoft approved these changes
LGTM

2021-03-18 11:50 UTC, merged